logging:
  version: 1

  formatters:
    simple:
      format: "[%(levelname)s] [%(name)s]: %(message)s"

    complex:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"


  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple

    file:
      class: logging.handlers.RotatingFileHandler
      maxBytes: 10485760  # 10 MB
      backupCount: 5
      level: DEBUG
      formatter: complex
      filename : monitor.log

  loggers:
    Worker:
      level: INFO
      handlers: [console]
      propagate: yes

    HttpMonitor:
      level: INFO
      handlers: [console]
      propagate: yes

    Dispatcher:
      level: INFO
      handlers: [console]
      propagate: yes

    Translator:
      level: INFO
      handlers: [console]
      propagate: yes

    HttpClient:
      level: INFO
      handlers: [ console ]
      propagate: yes


monitoring:
  aliases:
    seoji_monitor: &seoji_monitor
      # url: "http://seoji.nl.go.kr/landingPage/SearchAjax.do"
      url: "http://localhost:8080/get_isbn"
      timeout: 999
      check_every: 3
      method: 'GET'

    seoji_payload: &seoji_payload
      fq_select: "tSrch_total"
      facet.field: "EBOOK_YN"
      sort: "INPUT_DATE DESC"
      wt: "json"
      rows: 10
      start: 0
      page: 1


  monitors:
    seoji1:
      <<: *seoji_monitor
      description: "seoji-1"
      payload:
        <<: *seoji_payload
        tSrch_total: "(연재) 삽화가 2021"
        q: "(연재) 삽화가 2021"

    seoji2:
      <<: *seoji_monitor
      description: "seoji-2"
      payload:
        <<: *seoji_payload
        tSrch_total: "(연재) 삽화가 2021"
        q: "(연재) 삽화가 2021"

    seoji3:
      <<: *seoji_monitor
      description: "seoji-3"
      payload:
        <<: *seoji_payload
        tSrch_total: "(연재) 삽화가 2021"
        q: "(연재) 삽화가 2021"

    seoji4:
      <<: *seoji_monitor
      description: "seoji-4"
      payload:
        <<: *seoji_payload
        tSrch_total: "(연재) 삽화가"
        q: "(연재) 삽화가"